name: deployment

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

env:
# NODE_ENV: development
# DB_NAME: naruto
# DB_USER: naruto
# DB_PASSWORD: naruto
# PORT=9090

jobs:
  deploy:
  runs-on: ubuntu-latest
    steps:
      -name: ssh to pull latest version
      uses: fifsky/ssh-action@master
      with:
      command: |
        cd BAD-NARUTO/
        git pull
        npm install
        yarn knex migrate:latest 
        forever restart 0
      host: www.aininja.games
      user: ubuntu
      key: ${{secrets.SSH_PRIVATE_KEY}}